name: Hello Actions
on:
  push:
    branches:
    - master    
  pull_request:
    types: [closed]
  workflow_dispatch:
env:
  name: Streetyogi
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      name: Miron T
    steps:
      - name: Run a one-line script
        run: |
          echo Hello, $name!
          echo Actor: ${{ github.actor }}
          echo Commited By: ${{ github.event.commits[0].author.name }}
  flight:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Airplaines
        env: 
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python -c '
          import http.client
          import os;
          API_KEY = os.environ["API_KEY"]
          conn = http.client.HTTPSConnection("flight-radar1.p.rapidapi.com")
          headers = {
            "X-RapidAPI-Key": f"{API_KEY}",
            "X-RapidAPI-Host": "flight-radar1.p.rapidapi.com"
          }
          conn.request("GET", "/aircrafts/list", headers=headers)
          res = conn.getresponse()
          data = res.read()
          print(data.decode("utf-8"))
          '
  dump:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run:
          echo "$GITHUB_CONTEXT"
  pull_request_only:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: build
    steps:
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo Hi, $name.
